
@api = http://localhost:3001/products

GET {{api}}

###

POST {{api}}
Content-Type: application/json

{
    "name": "otro producto",
    "description": "algo www",
    "quantity": 122
}
###

GET {{api}}/10
###

DELETE {{api}}/9
###

GET {{api}}/count
###

PUT {{api}}/14
Content-Type: application/json

{
    "name": "arreglado",
    "description": "algo ssss",
    "quantity": 1222
}

